=== olgagitskaya/backup_Task05/Task05_Volha_Hitskaya/Menu.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.epam.com/menu"
            xmlns:tns="http://www.epam.com/menu"
            elementFormDefault="qualified">

    <xsd:element name="menu">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="category" type="tns:category" minOccurs="1" maxOccurs="12"></xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType  name="category">
        <xsd:sequence>
            <xsd:element name="dish" type="tns:dish" minOccurs="1" maxOccurs="unbounded"></xsd:element>
        </xsd:sequence>
        <xsd:attribute name = "categoryName" type = "xsd:string"/>
    </xsd:complexType>

    <xsd:simpleType name="categoryName">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="холодные закуски"/>
            <xsd:enumeration value="горячие закуски"/>
            <xsd:enumeration value="завтраки"/>
            <xsd:enumeration value="салаты"/>
            <xsd:enumeration value="супы"/>
            <xsd:enumeration value="рыбные блюда"/>
            <xsd:enumeration value="мясные блюда"/>
            <xsd:enumeration value="гарниры"/>
            <xsd:enumeration value="блюда на мангале"/>
            <xsd:enumeration value="от шеф-повара"/>
            <xsd:enumeration value="приложение"/>
            <xsd:enumeration value="десерт"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="dish">
        <xsd:sequence>
            <xsd:element name="photo" type="xsd:string" />
            <xsd:element name="title" type="xsd:string" />
            <xsd:element name="description" type="xsd:string" />
            <xsd:element name="portion" type="xsd:string" />
            <xsd:element name="price" type="xsd:nonNegativeInteger" default="0"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:positiveInteger" use="required"></xsd:attribute>
    </xsd:complexType>
</xsd:schema>

=== olgagitskaya/backup_Task05/Task05_Volha_Hitskaya/Menu.xml
<?xml version="1.0" encoding="UTF-8"?>

<menu xmlns="http://www.epam.com/menu"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.epam.com/menu Menu.xsd">

    <category categoryName="холодные закуски">
        <dish id="1">
            <photo>Фото блюда</photo>
            <title>Ассорти рыбное</title>
            <description>Слабосоленая форель, семга</description>
            <portion>100/20/15</portion>
            <price></price>
        </dish>
        <dish id="2">
            <photo>Фото блюда</photo>
            <title>Тарталетки с красной икрой</title>
            <description>Тарталетки с красной икрой</description>
            <portion>60/50</portion>
            <price></price>
        </dish>
        <dish id="3">
            <photo>Фото блюда</photo>
            <title>Закуска по-русски</title>
            <description>Кусочки атлантической сельди с отварным картофелем, луком, лимоном и зеленью</description>
            <portion>70/50/2/10</portion>
            <price></price>
        </dish>
    </category>
    <category categoryName="горячие закуски">
        <dish id="1">
            <photo>Фото блюда</photo>
            <title>Лобио с шампиньонами</title>
            <description>Фасоль с шампиньонами и грецким орехом</description>
            <portion>150/5</portion>
            <price>105</price>
        </dish>
        <dish id="2">
            <photo>Фото блюда</photo>
            <title>Жульен</title>
            <description>с курицей</description>
            <portion>120/1</portion>
            <price>145</price>
        </dish>
        <dish id="3">
            <photo>Фото блюда</photo>
            <title>Жульен</title>
            <description>с грибами</description>
            <portion>120/1</portion>
            <price>155</price>
        </dish>
    </category>
    <category categoryName="завтраки">
        <dish id="1">
            <photo>Фото блюда</photo>
            <title>Глазунья</title>
            <description>2 яйца (на выбор ветчина, сыр, помидоры)</description>
            <portion>150</portion>
            <price></price>
        </dish>
        <dish id="2">
            <photo>Фото блюда</photo>
            <title>Омлет</title>
            <description></description>
            <portion>100</portion>
            <price></price>
        </dish>
        <dish id="3">
            <photo>Фото блюда</photo>
            <title>Блинчики с мясом</title>
            <description>Жареные блинчики с мясом</description>
            <portion>150</portion>
            <price></price>
        </dish>
    </category>
<!--    <category categoryName="салаты"></category>
    <category categoryName="супы"></category>
    <category categoryName="рыбные блюда"></category>
    <category categoryName="мясные блюда"></category>
    <category categoryName="гарниры"></category>
    <category categoryName="блюда на мангале"></category>
    <category categoryName="от шеф-повара"></category>
    <category categoryName="приложение"></category>
    <category categoryName="десерт"></category> -->
</menu>
